# Generated by Django 5.2.3 on 2025-06-15 17:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Company description', null=True)),
                ('tenant_id', models.UUIDField(help_text='ID of the tenant this company belongs to (from auth service)')),
                ('created_by', models.UUIDField(help_text='ID of the user who created this company (from auth service)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the company was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the company was last updated')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'tenant_id'), name='unique_company_name_per_tenant')],
            },
        ),
    ]
